### ISSUE TITLE
No issues [migrations]

### ISSUE THREAD

**Issue by cilsilver** [leantony/ecommerce#1]
Hi, I was wanting to learn in e-commerce and i stumbled on your app. really nice but i was having challenges understanding your schemas. I noticed you have excluded your migrations. Please is there a way to get them to help me out. Spent hours trying to figure out but couldn't. Thanks.

**Comment by leantony** [comment]
Yeah about the migrations. Sorry, I didn't use them. For now though, You
can check out the schema via this link
https://www.dropbox.com/s/sxb5qjgzuqlubb5/ecommerce.sql.tar.gz?dl=0

**Comment by cilsilver** [comment]
Oh great, thanks. I will check right away
Sent from my BlackBerry wireless device from MTN

-----Original Message-----

**Comment by cilsilver** [comment]
Thanks for the link. I got it. Appreciate

**Comment by leantony** [comment]
Oh, ive uploaded the migrations in the most recent commit

**Comment by cilsilver** [comment]
Oh i got it. thanks a lot

**Comment by MuratSaka** [comment]
hi leantony 
I was try in localhost your package but its gave  below error can you help is possible?

file_put_contents(/967e487cf0280d54c68d5a16b3b10270): failed to open stream: Permission denied

**Comment by MuratSaka** [comment]
what can I do ?

and I changed datatables somethings' gave syntox problem I send with migration localhost but I saw abowe problem  chmod command wants  how can I write chmod command excatly
thanks
