### ISSUE TITLE
White screen

### ISSUE THREAD

**Issue by cilsilver** [leantony/ecommerce#2]
Thanks for the usual responses. I tried using the migrations after composer install but showing white screen. with fresh set up
what could have been causing this? 

localhost:8000 not [white screen]
localhost:8000/myaccount [white screen]

**Comment by leantony** [comment]
Sorry for the late reply. The issue is down to the fact that the shopping cart does not exist. The function that checks for this returns nothing, hence the blank page. But its okay now. I fixed it in the latest commit

**Comment by leantony** [comment]
And some routes are ssl protected, so just create a self signed certificate and use that

**Comment by cilsilver** [comment]
Thanks for the quick response, trying to generate the self certificate. trying to figure it out here http://www.akadia.com/services/ssh_test_certificate.html

**Comment by cilsilver** [comment]
Do you have any plan upgrading to L5.1?

**Comment by leantony** [comment]
Yes. Just waiting for package dependancies to be updated

**Comment by cilsilver** [comment]
Upgraded to L5.1!!! Wow! You are just super awesome! you always bringing support for newbie developers too. Great contributions from you. THANKS

**Comment by cilsilver** [comment]
Please why is it bringing such error thanks? FatalErrorException in AuthController.php line 46:
Call to undefined function App\Http\Controllers\Shared\eq()

**Comment by leantony** [comment]
Sorry for the late reply. I've just seen this now. The function eq() exists in app\Antony\helpers.php. Check if the copy you have has this function:

if (!function_exists('eq')) {

```
/**
 * Checks if two values are equal
 *
 * @param $value1
 * @param $value2
 * @param bool $strict
 *
 * @return bool
 */
function eq($value1, $value2, $strict = true)
{

    return $strict ? $value1 === $value2 : $value1 == $value2;
}
```

}

If it doesn't just copy the one above there. By the way, its just a fancy function that checks if two values are equal. In this case, it will check if the request segment at index 1 is equal to 'backend'. So, you can just replace the line eq($request->segment(1), 'backend') ? true : false; 
to $request->segment(1) === 'backend' ? true : false;

**Comment by cilsilver** [comment]
Oh great! thanks.. Really working hard to study the code bit by bit

I tried it again, it still shows the same error. but if i comment it, it never shows the error.

  public function __construct(AuthenticateUser $authenticateUser, RegisterUser $registerUser, Request $request)
    {  
        $this->backend = eq($request->segment(1), 'backend') ? true : false;

```
}
```

**Comment by cilsilver** [comment]
Now resolved, it worked perfectly with this [ $request->segment(1) === 'backend' ? true : false;]

Just brought up another error.. still trying to figure out to solve it
IFatalErrorException in b09ddc46e5f32d3a3a19002b0cca514d line 3:
Call to undefined function api_login_enabled()

**Comment by leantony** [comment]
Probably youre working from scratch. I dont know, but if youre using the latest version of the repo, you shouldnt be getting such errors. The function api_login_enabled() exists in app\antony\helpers.php.

**Comment by leantony** [comment]
https://github.com/leantony/ecommerce/blob/master/app/Antony/helpers.php#L19
