### ISSUE TITLE
BindingResolutionException in Container.php line 744

### ISSUE THREAD

**Issue by cilsilver** [leantony/ecommerce#3]
BindingResolutionException in Container.php line 744:
Target [app\Antony\DomainLogic\Contracts\Caching\CacheInterface] is not instantiable.
What does this means please? Thanks

**Comment by leantony** [comment]
It means there's no binding or abstract specified in the AppServiceProvider that would bind the CacheInterface to a concrete class during runtime. So, in the AppServiceProvider, check for the following lines of code, and if they don't exist, add them.

// binding the cache interface to our laravelCache class
$this->app->bind('app\Antony\DomainLogic\Contracts\Caching\CacheInterface', function ($app) {
       return new LaravelCache($app['cache']);
});

**Comment by leantony** [comment]
https://github.com/leantony/ecommerce/blob/master/app/Providers/AppServiceProvider.php#L41

**Comment by cilsilver** [comment]
thanks my friend
