### ISSUE TITLE
[Illuminate\Database\QueryException]

### ISSUE THREAD

**Issue by cilsilver** [leantony/ecommerce#4]
I noticed this has been happening anytime i rollback or try new migrations. So i commented it before other migrations can be migrated which i know it's not advisable for production development.
Any idea on how to solve this? Thanks for the supports so far.
php artisan migrate:
Error->;
[Illuminate\Database\QueryException]
SQLSTATE[42000]: Syntax error or access violation: 1170 BLOB/TEXT column 'description_long' used in key specification without a key length (SQL: alter table `products` add i
e`(`name`,`description_long`))

[PDOException]
SQLSTATE[42000]: Syntax error or access violation: 1170 BLOB/TEXT column 'description_long' used in key specification without a key length

**Comment by leantony** [comment]
Try dropping the index 'description_long' from the db schema. I created the
db sometime back, and currently the index isn't even used. So try replacing
the products_table migration with this;

<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;

class CreateProductsTable extends Migration {

/**
 * Run the migrations.
 *
 * @return void
 */
public function up()
{
Schema::create('products', function(Blueprint $table)
{
$table->increments('id');
$table->integer('brand_id')->unsigned()->nullable()->default(0)->index('`FK_products_brands`');
$table->integer('category_id')->unsigned()->nullable()->default(0)->index('`FK_products_categories`');
$table->integer('subcategory_id')->unsigned()->nullable()->default(0)->index('`FK_products_sub_categories`');
$table->string('sku', 50)->unique('`sku`');
$table->string('name');
$table->integer('price')->unsigned();
$table->integer('shipping')->unsigned()->nullable()->default(0);
$table->float('discount', 10, 0)->unsigned()->nullable();
$table->integer('quantity')->unsigned();
$table->integer('available')->default(1);
$table->text('description_short', 65535)->nullable();
$table->text('description_long', 65535);
$table->text('stuff_included', 65535)->nullable();
$table->float('warranty_period', 10, 0)->unsigned()->nullable();
$table->binary('image', 65535);
$table->binary('image_large', 16777215)->nullable();
$table->boolean('zoomable')->default(1);
$table->integer('free')->unsigned()->default(0);
$table->integer('taxable')->unsigned()->default(1);
$table->timestamps();
$table->softDeletes();
});
}


/**
 * Reverse the migrations.
 *
 * @return void
 */
public function down()
{
Schema::drop('products');
}

}

**Comment by leantony** [comment]
Ive removed the index. This should work. Just replace your products-table-migration copy with this one.

https://gist.github.com/leantony/fb6e7fc05978be14d8f9#file-products-table-migration-php

**Comment by cilsilver** [comment]
Nice! it works like magic. Thanks
