### ISSUE TITLE
CSS 

### ISSUE THREAD

**Issue by cilsilver** [leantony/ecommerce#5]
How do you manage your CSS? I noticed you excluded your npms. With new installation approach, how do i reference all the CSS? the views are not styled.

Thanks

**Comment by leantony** [comment]
It wouldn't make sense to upload all node modules to GitHub. I use bower. Check for the bower script in resources/views. Then run the command => bower install

Assuming of course you have both node and bower. I use elixir to compile less, concatenate all my js, and style-sheets. After bower install is done, run the command => gulp default

**Comment by cilsilver** [comment]
Thanks a lot for the information
