### ISSUE TITLE
Error while running composer update

### ISSUE THREAD

**Issue by bosz** [leantony/ecommerce#7]
Good day. 

I was trying to set up your project on my local machine. 
I used compose update to get the vendor folder and all dependencies. 

I get this error almost at the end of the process

Script php artisan ide-helper:generate handling the post-update-cmd event returned with an error

  [RuntimeException]  
  Error Output:       

update [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--lock] [--no-plugins] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--with-dependencies] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [packages1] ... [packagesN]

root@ech310n-Latitude-D430:/home/ech310n/ecommerce/ecommerce# php artisan ide-helper:generate
Exception: No supported encrypter found. The cipher and / or key length are invalid.
Skipping \Illuminate\Support\Facades\Crypt.
Exception: No supported encrypter found. The cipher and / or key length are invalid.
Skipping \Illuminate\Support\Facades\Password.
Exception: No supported encrypter found. The cipher and / or key length are invalid.
Skipping \Illuminate\Support\Facades\Redirect.
Exception: No supported encrypter found. The cipher and / or key length are invalid.
Skipping \Illuminate\Support\Facades\Response.
Exception: No supported encrypter found. The cipher and / or key length are invalid.
Skipping \Laracasts\Flash\Flash.
Exception: No supported encrypter found. The cipher and / or key length are invalid.
Skipping \Collective\Html\FormFacade.

  [RuntimeException]  
  No supported encrypter found. The cipher and / or key length are invalid.  

---

Actually, i doubt if its an error in your code. Yet, maybe you can still help. 
Thanks.

**Comment by bosz** [comment]
when i run php artisan serve, it serves on localhost:8000
but when i try typing that url on the browser, i get "Whoops, looks like something went wrong."

This is the laravel error log

[2015-09-29 05:26:06] production.ERROR: exception 'RuntimeException' with message 'Required environment variable missing, or value not allowed: 'DB_HOST', 'DB_DATABASE', 'DB_USERNAME', 'DB_PASSWORD'' in /home/ech310n/ecommerce/ecommerce/vendor/vlucas/phpdotenv/src/Dotenv.php:121
Stack trace:
#0 /home/ech310n/ecommerce/ecommerce/app/Providers/EnvironmentServiceProvider.php(26): Dotenv::required(Array)
#1 [internal function]: App\Providers\EnvironmentServiceProvider->boot()
#2 /home/ech310n/ecommerce/ecommerce/vendor/laravel/framework/src/Illuminate/Container/Container.php(502): call_user_func_array(Array, Array)
#3 /home/ech310n/ecommerce/ecommerce/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(734): Illuminate\Container\Container->call(Array)
#4 /home/ech310n/ecommerce/ecommerce/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(717): Illuminate\Foundation\Application->bootProvider(Object(App\Providers\EnvironmentServiceProvider))
#5 [internal function]: Illuminate\Foundation\Application->Illuminate\Foundation{closure}(Object(App\Providers\EnvironmentServiceProvider), 20)
#6 /home/ech310n/ecommerce/ecommerce/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(718): array_walk(Array, Object(Closure))
#7 /home/ech310n/ecommerce/ecommerce/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/BootProviders.php(17): Illuminate\Foundation\Application->boot()
#8 /home/ech310n/ecommerce/ecommerce/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(203): Illuminate\Foundation\Bootstrap\BootProviders->bootstrap(Object(Illuminate\Foundation\Application))
#9 /home/ech310n/ecommerce/ecommerce/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(222): Illuminate\Foundation\Application->bootstrapWith(Array)
#10 /home/ech310n/ecommerce/ecommerce/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(117): Illuminate\Foundation\Http\Kernel->bootstrap()
#11 /home/ech310n/ecommerce/ecommerce/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(87): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#12 /home/ech310n/ecommerce/ecommerce/public/index.php(53): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#13 /home/ech310n/ecommerce/ecommerce/server.php(20): require_once('/home/ech310n/e...')
#14 {main}  
[2015-09-29 05:26:06] production.ERROR: exception 'RuntimeException' with message 'No supported encrypter found. The cipher and / or key length are invalid.' in /home/ech310n/ecommerce/ecommerce/vendor/laravel/framework/src/Illuminate/Encryption/EncryptionServiceProvider.php:29
Stack trace:
#0 /home/ech310n/ecommerce/ecommerce/vendor/laravel/framework/src/Illuminate/Container/Container.php(733): Illuminate\Encryption\EncryptionServiceProvider->Illuminate\Encryption{closure}(Object(Illuminate\Foundation\Application), Array)
#1 /home/ech310n/ecommerce/ecommerce/vendor/laravel/framework/src/Illuminate/Container/Container.php(626): Illuminate\Container\Container->build(Object(Closure), Array)
#2 /home/ech310n/ecommerce/ecommerce/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(674): Illuminate\Container\Container->make('encrypter', Array)
#3 /home/ech310n/ecommerce/ecommerce/vendor/laravel/framework/src/Illuminate/Container/Container.php(837): Illuminate\Foundation\Application->make('Illuminate\Cont...')
#4 /home/ech310n/ecommerce/ecommerce/vendor/laravel/framework/src/Illuminate/Container/Container.php(800): Illuminate\Container\Container->resolveClass(Object(ReflectionParameter))
#5 /home/ech310n/ecommerce/ecommerce/vendor/laravel/framework/src/Illuminate/Container/Container.php(771): Illuminate\Container\Container->getDependencies(Array, Array)
#6 /home/ech310n/ecommerce/ecommerce/vendor/laravel/framework/src/Illuminate/Container/Container.php(626): Illuminate\Container\Container->build('App\Http\Middle...', Array)
#7 /home/ech310n/ecommerce/ecommerce/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(674): Illuminate\Container\Container->make('App\Http\Middle...', Array)
#8 /home/ech310n/ecommerce/ecommerce/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(142): Illuminate\Foundation\Application->make('App\Http\Middle...')
#9 /home/ech310n/ecommerce/ecommerce/public/index.php(57): Illuminate\Foundation\Http\Kernel->terminate(Object(Illuminate\Http\Request), Object(Illuminate\Http\Response))
#10 /home/ech310n/ecommerce/ecommerce/server.php(20): require_once('/home/ech310n/e...')
#11 {main}

**Comment by leantony** [comment]
Sorry for the late reply
Youre getting your errors, because you don't have a .env file at the root of your project. This file stores sensitive credentials, like API keys, DB credentials, and the encryption key.
see => http://laravel.com/docs/5.1/installation#environment-configuration
In this case, youll create a .env file with

'DB_HOST', 'DB_DATABASE', 'DB_USERNAME', 'DB_PASSWORD'
A sample might look like this
see => https://github.com/laravel/laravel/blob/master/.env.example

**Comment by leantony** [comment]
once you have this file ready, just create the encryption key using the command

php artisan key:generate

Also, assets in the resources folder, e.g jquery, are managed by bower => bower.io, and laravel's elixir module

So make sure you have nodejs, gulp and bower installed on your machine

**Comment by leantony** [comment]
And by default, the .env file is not part of the git repo. Which is okay considering what it does store
You can see that in the default .gitignore file

https://github.com/laravel/laravel/blob/master/.gitignore
