### ISSUE TITLE
Uncaught UnexpectedValueException

### ISSUE THREAD

**Issue by xenxa** [leantony/ecommerce#9]
PHP Fatal error:  Uncaught UnexpectedValueException: The stream or file "/home/forge/default/storage/logs/laravel-2016-01-15.log" could not be opened: failed to open stream: No such file or directory in /home/forge/default/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:84

**Comment by leantony** [comment]
There's a problem with your file/folder  permissions. Try this

``` sh
sudo chown $USER:$USER - R home/forge/default/storage/*
```

**Comment by vignesh-subash** [comment]
I am getting this error. Help me to resolve this.

> chown: -: No such file or directory
> chown: R: No such file or directory

**Comment by leantony** [comment]
Try chown -R $USER:$USER  /home/forge/

Then run the app again
